import FormAddProduct, { uniqueId } from "@/components/formAddProduct"
import ProductView from "@/components/productView"
import { useActions } from "@/hooks/useActions"
import { useTypedSelector } from "@/hooks/useTypeSelector"
import ProductLayout from "@/layouts/productLayout"
import Head from "next/head"


import { FC, useEffect } from "react"


const NewProduct: FC = () => {

    const { removeItem, setProducts } = useActions()

    useEffect(() => {
        if (localStorage.products != "null") {
            setProducts(JSON.parse(localStorage.getItem("products") || ""))
        }
    }, [])

    return (
        <>
            <Head>
                <title>Добавление товара</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                />
            </Head>
            <ProductLayout title="Добавление товара">
                <FormAddProduct />
            </ProductLayout>
        </>

    )
}

export default NewProduct  