import ProductView from "@/components/productView"
import { useActions } from "@/hooks/useActions"
import { useTypedSelector } from "@/hooks/useTypeSelector"
import ProductLayout from "@/layouts/productLayout"
import IProduct from "@/types/product.type"
import { Head } from "next/document"
import { FC, useEffect } from "react"


const Catalog: FC = () => {

    const { products } = useTypedSelector(store => store)

    let ProductsPros: IProduct[] = products

    const initProductsProps = async () => {

        let response = await fetch("https://dummyjson.com/products?limit=10")

        if (response.ok) {

            let json = await response.json()
            ProductsPros = [...products, ...json.products]
        } else {
            alert("Ошибка HTTP: " + response.status)
        }
    }

    useEffect(() => {
        initProductsProps()
    }, [])

    const loadProducts = async (page: number) => {

        let response = await fetch(`https://dummyjson.com/products?skip=${page * 10}&limit=10`)

        if (response.ok) {

            let json = await response.json()
            ProductsPros = [...ProductsPros, ...json.products]
        } else {
            alert("Ошибка HTTP: " + response.status)
        }
    }

    return (
        <>
            {/* <Head>
                <title>Каталог</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                />
            </Head> */}
            <ProductLayout title="Каталог">
                <ProductView products={ProductsPros} loadFunc={loadProducts} />
            </ProductLayout>
        </>

    )
}

export default Catalog