import ProductView from "@/components/productView"
import ProductLayout from "@/layouts/productLayout"
import { Head } from "next/document"
import { FC } from "react"


const Catalog: FC = () => {

    return (
        <>
            <Head>
                <title>Каталог</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                />
            </Head>
            <ProductLayout title="Каталог">
                <ProductView deleteProduct={false} />
            </ProductLayout>
        </>

    )
}