import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import BasicSelect from '@/components/select'
import myStyles from '@/styles/myStyles.module.scss'
import BasicTextFields from '@/components/textInput'
import MultilineTextFields from '@/components/multiline'
import BasicButtons from '@/components/button'





const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
      </Head>
      <main className={styles.main}>
        <div className={myStyles.topBlock}>
          <h1>
            Добавление товара
          </h1>
          <BasicSelect />
        </div>
        <div className='product'>
          <div className='product__add'>
            <form action="">
              Наименование товара
              <BasicTextFields />
              Описание товара
              <MultilineTextFields />
              Ссылка на изображение товара
              <BasicTextFields />
              Цена товара
              <BasicTextFields />
              <BasicButtons />
            </form>


          </div>
          <div className='product__show'>

          </div>
        </div>
      </main>
    </>
  )
}
