import { Head } from "next/document"
import React, { useEffect, useState } from "react"
import myStyles from '@/styles/myStyles.module.scss'
import BasicSelect from "@/components/select"
import IProduct from "@/types/product"
import IProductLayoutProps from "@/types/productLayout"



const ProductLayout: React.FC<IProductLayoutProps> = ({ title, content }) => {

    const [products, addProducts] = useState<IProduct[]>([{ image: "", name: "", description: "", price: null }])

    useEffect(() => {

        addProducts(localStorage.products ? JSON.parse(localStorage.getItem("products") || "") : [{
            image: "https://pixel24.ru/page_images/images/08-eos-r-adaptors-control-ring-customise-function-v4_161193699623451.jpg",
            name: "Фотоаппарат",
            description: "Довольно-таки интересное описание товара в несколько строк. Довольно-таки интересное описание товара в несколько строк.",
            price: 10000
        },
        {
            image: "https://www.yarkiy.ru/system/uploads/preview/photo_storage/36413/PowerShot-SX620-HS-BK-FSL.jpg",
            name: "Фотоаппарат",
            description: "Довольно-таки интересное описание товара в несколько строк. Довольно-таки интересное описание товара в несколько строк.",
            price: 100000
        }
        ])

    }, [])


    const sortName = () => {
        const strName = products ? [...products].sort((a, b) =>
            a.name > b.name ? 1 : -1,
        ) : []
        addProducts(strName)
    }

    const sortAscending = () => {
        const numAscending = products ? [...products].sort((a, b) => (a.price && b.price) ? a.price - b.price : 0) : []
        addProducts(numAscending)
    }

    const sortDescending = () => {
        const numDescending = products ? [...products].sort((a, b) => (a.price && b.price) ? b.price - a.price : 0) : []
        addProducts(numDescending)
    }

    return (
        <>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link
                    rel="stylesheet"
                    href="https://fonts.googleapis.com/icon?family=Material+Icons"
                />
            </Head>
            <div className={myStyles.topBlock}>
                <h1>{title}</h1>
                <BasicSelect name={() => sortName()} ascending={() => sortAscending()} descending={() => sortDescending()} />
            </div>
            <div className={myStyles.wrapper}>
                {content}
            </div>
        </>
    )
}
export default ProductLayout
